### ISSUE TITLE
standardize sidebar styles so we can open it up to modification from the admin screen

### ISSUE THREAD

**Issue by skippy** [sjifire/website#123]
we're close!  However, contact has issues because it needs classname `block-content`

I *think* it's worth moving to the sidebar instead of hardcoding...but I can be talked out of it! :)

**Comment by icegulch** [comment]
i'm all for moving away from hardcoding! it's probably just a legacy thing, as that was the first page i added with a sidebar.

**Comment by icegulch** [comment]
ok. checked in branch `iss123`. let me know what you think, and of course if i've overlooked anything!

**Comment by skippy** [comment]
I'm going to close this for now... I think we got there.
