### ISSUE TITLE
add an About/Staff page

### ISSUE THREAD

**Issue by skippy** [sjifire/website#124]
need content and photos before we can flush this out.

**Comment by kvenegassjifire** [comment]
Have gathered professional photos of dept members now and would like to add this page. My suggestion is to call the page "Emergency Responders" and I can label each responder with the correct description like Firefighter/EMT or Support. Let me know what I can do to assist with implementing and upkeep.

**Comment by skippy** [comment]
@icegulch lets put this in the about us section, and make the page have a text field up top, then an alphabetical list... have the image and display name be configurable in the admin

**Comment by skippy** [comment]
@kvenegassjifire where are all the photos? Can you send them over so we can pre-load the system?

**Comment by icegulch** [comment]
@skippy @kvenegassjifire something like below?
[SJIFR-Emergency-Responders.pdf](https://github.com/sjifire/website/files/10310758/SJIFR-Emergency-Responders.pdf)

**Comment by kvenegassjifire** [comment]
Folder of those images [https://drive.google.com/drive/folders/1Rshy-FScU0menzfMG2o28fRWZV4V5y0J?usp=share_link](url)

**Comment by skippy** [comment]
@icegulch we'll also need a placeholder icon for folks who don't have an image.

**Comment by skippy** [comment]
@kvenegassjifire do we want to make this the 'Who We Are' page?  It seems like a good fit...!

**Comment by icegulch** [comment]
Just to track email conversations...

![SJIFR-Emergency-Responders-V2](https://user-images.githubusercontent.com/794708/209881520-a38a8ad9-98b0-4f43-a915-d3672bb5c043.png)
![SJIFR-Emergency-Responders-V3](https://user-images.githubusercontent.com/794708/209881523-84219ef7-2642-407b-8230-36826dc409e3.png)

**Comment by skippy** [comment]
@icegulch can we get 3 things, and then I can code this up:
* styles for title & rank, as in your image (I think we need them, but kelsey may not want them... can we style them up and then we can decide whether or not to show them later on?)
* a default image if there is no image

I guess that is only two!  Once I have those, I can fill in the rest, and then link it in once I have the initial copy.

**Comment by icegulch** [comment]
Alright, snuck in what I could tonight (sick kid during the day), but I think I can knock this one out in the early morning tomorrow...More soon!

**Comment by icegulch** [comment]
Hi, @skippy! I just pushed up changes that should take care of the potential addition of Title, Rank fields, as well as a conditional for people with no profile image. 

...oops! just saw the `-improved` branch. pushing everything up there now. sorry for missing that!

**Comment by skippy** [comment]
@kvenegassjifire @icegulch it's up,  with navigation as well.  

@kvenegassjifire we need to do two things to finish this up:
* copy (removed lorem ipsum for now).  You can add this via the admin screen
* notify members and ask them to verify that their roles are correct.  For example, I don't know everyone on the marine team,  etc.  


I'm happy to shoot a note out to all-personnel and ask folks to verify, OR perhaps first run it by Noel to see if he has any changes he wants to make?  Again, happy to run with that one.

**Comment by kvenegassjifire** [comment]
Thanks Adam! I will try to login and writeup everything I know tonight after bed or over the weekend when I have some time. I'll run the draft by Noel before we publish.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by skippy** [comment]
@kvenegassjifire are we good to go on this one?  If so, we can close it out.
