### ISSUE TITLE
typography spacing on lists

### ISSUE THREAD

**Issue by skippy** [sjifire/website#138]
https://www.sjifire.org/news/2022-01-18-we-are-an-ems-agency/

is it worth giving the list a bit more breathing space?

**Comment by icegulch** [comment]
Just checked in `iss138` with new spacing for both `<ol>` and `<ul>` tags. There's an example of an `<ol>` tag on `/news/2021-12-21-why-do-we-respond-to-medical-calls/`. Let me know what you think.

**Comment by skippy** [comment]
@icegulch two issues:
*

**Comment by skippy** [comment]
@icegulch huh!  I thought the spacing on gov was messed up, but it isn't anymore?  I may be seeing things.  Closing as #144 is open for it's specific issue
