### ISSUE TITLE
Modify burn ban levels and colors

### ISSUE THREAD

**Issue by skippy** [sjifire/website#270]
levels should be:
* low: green
* moderate: yellow
* High: red, like closed. 
* Extreme: dark red

**Comment by icegulch** [comment]
New PR for this change...lemme know if there are any issues...
![ 2022-12-27 at 13 31 05](https://user-images.githubusercontent.com/794708/209719309-b48886f9-010b-4cad-bbb3-c0cd87223938.png)

**Comment by skippy** [comment]
looks good!
