### ISSUE TITLE
Change banner photo

### ISSUE THREAD

**Issue by kvenegassjifire** [sjifire/website#294]
Change Banner photo on homepage. Emailed Adam the file

**Comment by kvenegassjifire** [comment]
![107312464_2982819008496203_2405639055351826895_n](https://user-images.githubusercontent.com/112978089/196766302-95a28d37-dcfb-435e-bc7b-a89ea334f036.jpg)

**Comment by kvenegassjifire** [comment]
![AllDeptPhoto2022](https://user-images.githubusercontent.com/112978089/196766335-cf58435a-51e9-410c-b23f-f6eac057652a.jpg)

**Comment by skippy** [comment]
@icegulch should we look at:
- make the image configurable; right now it is hard coded
- moving any layers/filters to the media upload process?  ie, if @kvenegassjifire makes the image the right size and crop, the upload process will take care of the rest?

**Comment by icegulch** [comment]
Hey @skippy ! I need to turn on my GH alerts...sorry I didn't see this yesterday. Anyhow, pushed up a new branch `iss294` that _should_ work. I'm having a hard time testing because I don't have my Netlify login or Cloudinary creds.

**Comment by icegulch** [comment]
@skippy there's now a pull request for this, if you don't mind testing.

**Comment by icegulch** [comment]
![ 2022-12-27 at 12 39 52](https://user-images.githubusercontent.com/794708/209719363-0e83746c-43a1-446e-a303-a4fa976913fa.png)

What it should look like...

**Comment by skippy** [comment]
@icegulch and @kvenegassjifire merged in as @kvenegassjifire I know you wanted this fixed.  However, I think we need to make the image pop a bit more.  @icegulch what do you think?

**Comment by kvenegassjifire** [comment]
> @icegulch and @kvenegassjifire merged in as @kvenegassjifire I know you wanted this fixed. However, I think we need to make the image pop a bit more. @icegulch what do you think?

Agreed, needs some tweaking. Could we do a washout on the color instead of black and white?

**Comment by icegulch** [comment]
Can definitely do something like the attached...however, if we take a step back for a second, any reason to revisit the existence of the banner photo itself?

About 99% of other fire websites use them (probably because the department's using some kind of WordPress theme that demands big banner photos), but they usually don't look good on wide screens...unless they truly are "background texture" as opposed to something with a focal point. 

![SJIFR-Landing-V2a](https://user-images.githubusercontent.com/794708/209858371-03b1206b-0abc-42ad-aa87-43f40dbc7338.png)
![SJIFR-Landing-V2a-widescreen](https://user-images.githubusercontent.com/794708/209858490-eefe6642-7d01-4b13-9d16-1c8b34eb96f1.png)

One of the few sites I can find _without_ a banner: https://www.sccfd.org/

Just thinking out loud...

**Comment by kvenegassjifire** [comment]
> Can definitely do something like the attached...however, if we take a step back for a second, any reason to revisit the existence of the banner photo itself?
> 
> About 99% of other fire websites use them (probably because the department's using some kind of WordPress theme that demands big banner photos), but they usually don't look good on wide screens...unless they truly are "background texture" as opposed to something with a focal point.
> 
> ![SJIFR-Landing-V2a](https://user-images.githubusercontent.com/794708/209858371-03b1206b-0abc-42ad-aa87-43f40dbc7338.png) ![SJIFR-Landing-V2a-widescreen](https://user-images.githubusercontent.com/794708/209858490-eefe6642-7d01-4b13-9d16-1c8b34eb96f1.png)
> 
> One of the few sites I can find _without_ a banner: https://www.sccfd.org/
> 
> Just thinking out loud...

Totally understand where you're coming from but I do think we should keep the banner, small town department vs big city dept and all that. I want to try and avoid using a lot of red on the homepage because it reads as too aggressive to me and is something I'm trying to fix PR-wise. Could we try a gold filter or something like this?

![AllDeptPhoto2022_washout](https://user-images.githubusercontent.com/112978089/209883031-43903d11-a945-4490-b46b-fa75f31f7092.jpg)
![deptvehicles_washout](https://user-images.githubusercontent.com/112978089/209883039-bf23267f-680c-4c8d-b617-896dde005eaf.jpg)

**Comment by icegulch** [comment]
Good weekend, @kvenegassjifire and @skippy! The week got away from me (catching up after school / daycare break, etc), but I'm back in the saddle.

Anyhow, I like the idea of gold...will experiment this weekend as time allows. More soon!

**Comment by icegulch** [comment]
Quick experiment @kvenegassjifire. Let me know what you think...darker gold? lighter? happy to explore more options or roll with it. :)

![homepage-gold-1](https://user-images.githubusercontent.com/794708/211163231-5ffce26f-42cb-49bd-a648-98e2df6b784c.png)
![homepage-gold-2](https://user-images.githubusercontent.com/794708/211163237-1d9ef37e-243d-48b6-8232-c405c54653ba.png)

**Comment by kvenegassjifire** [comment]
A little lighter I think? Closer to the "gold" in our logo (even though I realize it's actually yellow, pet peeve of mine haha). Thanks for trying it out!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by icegulch** [comment]
Thanks for the speedy feedback, @kvenegassjifire! Here's a lighter gold-yellow...whaddya think?

![homepage-gold-banner-2a](https://user-images.githubusercontent.com/794708/211166298-4f0e7607-0162-40cb-878f-e485559d8ec6.png)
![homepage-gold-banner-2b](https://user-images.githubusercontent.com/794708/211166301-24bd3e2d-7ac2-4dea-9f43-f0b6b24f0302.png)

**Comment by kvenegassjifire** [comment]
Thanks for giving it a shot but I think we should scratch the gold idea. Just doesn't flow with the rest of the page as I'd hoped. Let's keep the banner a cool grey or something neutral. Is it possible to make the dept logo on the left side a bit bigger so those colors pop against the grey?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by icegulch** [comment]
oh, let's try that, @kvenegassjifire!! what about more of a blue-slate gray with a larger logo like so:

![home-banner-slate-v3a](https://user-images.githubusercontent.com/794708/211168478-a69789f6-2604-4005-96d3-0b8576fb64b9.png)
![home-banner-slate-v3b](https://user-images.githubusercontent.com/794708/211168483-4f75a922-1388-469e-a564-a6288b823399.png)

**Comment by kvenegassjifire** [comment]
Perfect, I really like that slate blue. I ran it by our chief and one of the firefighters to make sure it was different enough from the EMS blue and they agreed this slate looks good! Let's commit to that. Thank you!
________________________________
