### ISSUE TITLE
update district map

### ISSUE THREAD

**Issue by skippy** [sjifire/website#31]
the current map, on the /about page, is out dated.  Can we generate a graphic based upon the updated district has shown here?

https://www.google.com/maps/d/u/0/viewer?mid=1nXNMqwagMcA3r_gfxBkgf1By9m8A6RLM&ll=48.57251784236343%2C-123.06054210097658&z=11

**Comment by icegulch** [comment]
i embedded it on the page. that will allow folks to zoom in and out. work for you?

**Comment by skippy** [comment]
perhaps!  Let me leave this open and I'll discuss internally if we want to create a custom graphic rather than link to a google map.  Honestly, I think this is beyond 'good enough', but I'll find out.

**Comment by skippy** [comment]
the UI is a challenge... I find that if I scroll the mouse onto the map, stop, and then try to scroll again, the focus shifts to scrolling the map in and out vs the rest of the page.  is there a way to make this less clunky?  More static perhaps?  Lets review with low-hanging fruit in mind, and if not, lets punt this to v2 and review then

**Comment by skippy** [comment]
and here is a layer with station locations: https://www.google.com/maps/d/u/0/edit?mid=1Bty6xHPWzxrnIY6q6_jqJXQbcRkVWOa9&usp=sharing

I've also attached the official district map from the county.  [SJ Fire Distr 3_1.pdf](https://github.com/sjifire/website/files/7876453/SJ.Fire.Distr.3_1.pdf)

**Comment by icegulch** [comment]
totally agree about the scroll issue for these maps...annoying. how about just including an image with a link in the caption to the "interactive" map?

**Comment by skippy** [comment]
that would be great.  

The FD is working iwth the county GIS to start adding more data into its systems around locations of harbors, marine and helicopter LZs, 911 call boxes, fire stations and fire equip. caches, etc... as well as the response zone.  BUT, that is going to take awhile.  Meanwhile, something static that highlights our zones and the locations of our Firehouses would be great and cover the vast majority of our use cases

**Comment by icegulch** [comment]
![sjifire-district3](https://user-images.githubusercontent.com/794708/150554162-b0162a41-1174-4e58-9000-43463ab0f227.png)

So it's on the issue ticket too...
