### ISSUE TITLE
add more documents to the governance section

### ISSUE THREAD

**Issue by skippy** [sjifire/website#34]
right now we only have the board meeting minutes.  We need to add supplementary documents.  I think we can add them under each board meeting section, BUT we may need to have a general documents area for common/important documents.

I'm meeting with the chief in the coming days to get a handle on this.

**Comment by icegulch** [comment]
I may re-use the _advisory_ "card" layout for these...my initial thought anyhow.

**Comment by skippy** [comment]
sure; lets start with the version you mocked up, but in a v1.5 or so we'll probably want to have a little sidebar with common/important documents... 3-6 of them I guess?  general budget, etc.

**Comment by skippy** [comment]
addressed through a BUNCH of PRs
