### ISSUE TITLE
Overlay Background Color

### ISSUE THREAD

**Issue by icegulch** [sjifire/website#360]
Hey, @skippy . Sorry not to file this sooner! 

I mentioned when we last spoke that I noticed a little bug I introduced while tweaking the header background color. Indeed, you can see the issue here:

https://www.sjifire.org/news/2022-04-15-spring-st-fire-thoughts/

But the fix should be fairly trivial. If you change the variables in the `featured__media` rule, specifically the `background-image` rule, from `--dk-gray` to `--home_header_bg`, all should be right in the universe again. :)

I'm happy to fix this too, but I think you wanted to nab it? Regardless, just let me know!

Cheers,
Steve

**Comment by skippy** [comment]
fixed!  thanks sir
