### ISSUE TITLE
image handling

### ISSUE THREAD

**Issue by skippy** [sjifire/website#54]
Right now we have two approaches:
* admin screen: lots of technical detail needed (height/width); no editing, cropping, etc. 
* add it via the markdown widget: just post an image

Simpler is best, BUT I think we need to be able to have a few patterns that we can choose from for the layout of the image(s) on each page:
* a featured image on other pages besides posts would be great. 
* carousel's at the bottom?  Should this be an option on every page?  
* what about images mid-stream?  I'm less and less of a fan of the LIST approach, and think just the markdown widget for the main body is fine.  But using markdown-attr, can we have a bit more control (float-left, or float-right, or left, middle, right?).
* do we use a different image handler such as Cloudinary directly?  This may be an even BIGGER issue, and perhaps should be punted?
* OR can we use css and markdown-attr to better manage the images?  such as adding `{ width=60%,height:30px }` or a class?

I'm a TOTAL novice as to what the current tech is capable of; I remember when CSS was launched and it was such a big deal!  KISS is a great principle for the end user, so if we can do the work for them, that would be great.

**Comment by skippy** [comment]
ditto with the about page, esp. the map

**Comment by skippy** [comment]
@icegulch I added the markdown-attr plugins so we can add class attributes such as `float-left` or `float-right`...

**Comment by skippy** [comment]
@icegulch I can override the markdown -> image component so it asks for a few things like a dropdown of predefined classes, width/height fields or dropdowns if we want, etc... I would modify and overwrite the default Image component https://github.com/netlify/netlify-cms/blob/65343c1238af85e9151abb6bbba3770a08091176/packages/netlify-cms-editor-component-image/src/index.js


anyway, throwing that out there.  We can do this by figuring out the patterns we want to support, and then I can modify the admin screen to fit

**Comment by skippy** [comment]
dumped some images in /about/who-we-are/

to discuss and talk about what we can do to standardize image handling

**Comment by skippy** [comment]
I thik we have a bit of a plan; which is to stay the course, but provide improved handling of imgs into and from cloudinary.  Most of this work is being done in #70 

I'm going to leave this open but move it to v2; and then close after a bit more work and consolidation is done.

**Comment by skippy** [comment]
@icegulch  as a reminder, you're going to review the code flow and see if this is reasonable and fair, or too brittle and rigid.  IF you think the code and approach is in the right direction, lets discuss how to tighten it up so it is maintainable, and then close this out.  If it isn't the right approach, lets discuss!

**Comment by skippy** [comment]
1. yes.  It is live and up there.  Right now it just allows 3 img sizing options, but we can tweak that of course. 
2. I'm open to that!  The default is the large img that we see throughout the blog posts, but folks can use smaller sizes if they don't want to take up a huge amount of space for a CO Alarm, for example.  I'm totally open to changing that and moving more towards full_width, floated left, and floated right... why don't we use CO Alarm as the experiment?

**Comment by icegulch** [comment]
groovy! i'll take a crack at it tomorrow. gotta switch gears now...

**Comment by icegulch** [comment]
checked in `iss54` branch with a concept for randomly showing a different background image on page load. made it so images could be added via the admin (right now, they're just a setting in `site.json`). leveraging cloudinary params to prep the selected image for blending. rough now, but let me know if selecting on load works. we could do a repeating fade-between images, but that may be processing-heavy. let me know what you think...

**Comment by skippy** [comment]
per discussion, we're going to close this for now.... the header is added, cloudinary helpers are added, and we're going to see if we need to do anything more advance.
