### ISSUE TITLE
add ability to upload pdf or other document to posts

### ISSUE THREAD

**Issue by skippy** [sjifire/website#59]
as well as image

**Comment by skippy** [comment]
want to add the following 'Announcement' (back dated)

Title: Nov 2, 2021 Election: FAQs
Post Type: Announcement
Date: 2021-10-18
Lede: Frequently Asked Questions for the San Juan Island Fire & Rescue Emergency Medical Services Levy on the November 2nd, 2021 ballot.
[San-Juan-Fire-EMS-Levy-2021-FAQ.pdf](https://github.com/sjifire/website/files/7694438/San-Juan-Fire-EMS-Levy-2021-FAQ.pdf)

**Comment by icegulch** [comment]
We should be able to do this, no sweat. Maybe just decide on OneDrive first?

**Comment by skippy** [comment]
I'm going to take this one on.

**Comment by skippy** [comment]
fixed!
