### ISSUE TITLE
add directions to run admin screen locally

### ISSUE THREAD

**Issue by skippy** [sjifire/website#64]
`npm start` does great for the main site; but how do I get the admin screen to fire up on `localhost`

I'm sure this is super simple, but I'm not a nodeJS guy and can't seem to easily figure it out.

if this isn't easily doable, no worries... just hate to test admin on production

**Comment by icegulch** [comment]
yeah, i had trouble too. netlifycms has some instructions, but i can revisit and update the readme (if you haven't already done so!).

**Comment by skippy** [comment]
mostly addressed via: 86129e09b40d4e6e4c3b948055697f34aee87f86 and 0ba7e86f7303aa185d465bfc226689487be740b1

however, any changes go to the github main branch rather than the local branch... there are ways to run it locally but it gets a whole lot more convoluted if you need to save locally
