### ISSUE TITLE
consider authorship notes on posts

### ISSUE THREAD

**Issue by skippy** [sjifire/website#65]
for some posts, we may want to add authorship notes... such as general news, profiles, etc.

it would include Name, position (volunteer/staff/paid-part-time, etc), perhaps certifications/roles (ff, EMT-B/EMT-A, AO, Rope Rescue Tech, Marine Tech, hazmat tech, etc).

we can default to doing this just in the text block at the end of a post, but do we want to consider calling this out separately in the layout?

**Comment by icegulch** [comment]
sounds like a "people" model? and we could have a "null" and / or fallback option too.

**Comment by skippy** [comment]
yeah, an optional section.  BUT right now I'm the only one doing writing, so no need until I can get more to contribute on a regular basis

**Comment by skippy** [comment]
closing for now
