### ISSUE TITLE
stats widget

### ISSUE THREAD

**Issue by skippy** [sjifire/website#67]
on the home page.  This can be static (reading json file?) or even just coded HTML to start.  Longer term may have to create a cron job which goes out and processes a report into the format we need.  

TODO:
* stats needed
* ability to link to an explanation post about what the numbers mean, how we think about it, etc

**Comment by skippy** [comment]
the PDF being generated looks like: 
* https://www.sjifire.org/assets/docs/dec21-operations-report.pdf
* https://www.sjifire.org/assets/docs/nov21-operations-report.pdf

we can do a few things:
* show last 30 days and/or show last full month
* show downgraded/canceled
* time to arrival (nov report calls travel time aggregate)

I'm pretty sure the backend system can output a csv; I'm meeting the chief friday (12/17/21) to see how we can hook into that system.

**Comment by skippy** [comment]
brainstorm stats:
* personel
  * how many per (week, month, quarter); total and unique; full time staff vs volunteer/part-time
  * how much time responding per (week, month, quarter);
  * how many active in a week,month,quarter (training, call log)
  * hrs training
  * percent live in county
  * num volunteers; num staff; num administrative
* calls
  * num; downgraded/canceled; per district; out of district; type (ems/rescue/fire/marine/vehicle)
  * times (chute time, travel time, time to scene; time on scene (avg, longest)
  * personnel per call; most personnel on a call; most apparatus on a call
  * longest duration; most resources (# personnel; personnel hrs, most vehicles)

**Comment by skippy** [comment]
@icegulch this is up and running!  

Please don't judge me as a person because of the JS code... I have never really programmed in javascript except the occasional frontend stuff around JQuery 15 yrs ago; it's changed a LOT!  So lots of mixing of styles and a purist would spew into a little paper cup if they saw this.  But it works, has some basic functional tests for stability of the output interface... so we should be ready to go!

BUT, please take a look and let me know if you see anything worth fixing (glaring or otherwise).

the file is updated nightly to `src/_data/stats.json`; so you can build the frontend off of that.

**Comment by skippy** [comment]
@icegulch after discussion with the chief, lets start with:
* widget on the landing page (below advisories and above news?   Left side with burn status on right?)
* the following data which is available from `src/_data/stats.js` (all stats are in `seconds`)
```
total calls:
  - medical_rescue
  - fire and all other incidents
  - daytime and nighttime counts
  - total # of calls

personnel:
 - total time (min) of time of alarm to clear:
 ## NOTE: these next four could be optional based upon layout and design constraints
 - max personnel on an incident
 - min personnel for every incident
 - avg # of responders on an incident
 - min # of staffing on-call (this is 2+ min_personnel)

 call times:
 - reaction time: avg
 - travel time:
   - north: avg
   - central: avg
   - south: avg
 - on scene time: avg
```
* the chief noted a couple of good points: If we have to explain it, maybe we shouldn't display it; and less is more :)

and then in the widget, lets have a link that can explain number or details which links to a blog post which I'll write up and release simultaneous to the widgets going live.

thoughts?

**Comment by icegulch** [comment]
You've been busy!!! This all sounds super fun. Can't wait to take a look. Bravo!!

**Comment by skippy** [comment]
Updated design, signed off and ready to go @icegulch .  This is the same as what I sent in an email

```
Calls Last 30 days
------------------------
Calls: 79 (Last Year: 1008)
Reaction Times: 87 sec
Travel Times to Scene:
- North: 16.9 min
- Central: 6.4 min
- South: 13.9 min
Total Responder Time on Calls: 7,039 minutes
Responder Participation on Calls: 21
```
