### ISSUE TITLE
burn status widget

### ISSUE THREAD

**Issue by skippy** [sjifire/website#68]
show on the home page:
* fire danger level (green, yellow, red)
* burn status (and what does that mean)
* burn permit link

the burn status details and permit may need its own page, or at least show some high level with a link to details.  

see: https://www.sanjuanco.com/1088/Fire-Marshal

**Comment by skippy** [comment]
see the widget on https://www.orcasfire.org/

my thinking is what if we create a site config file that is editable from the admin screen but is pulled in to other pages?  kind of like an editable site.js file?  I can explore that AND make it editable IF you want to design and use hard-coded data for now, emulated what is on the Orcas Fire website.

**Comment by icegulch** [comment]
Sounds good. Anything that goes into the 11ty '/_data/' folder is globally available, so this should be pretty straightforward.

**Comment by skippy** [comment]
at the bottom of the widget, link to the `burn permit` page at `/services/burn-permits`.  see #94

**Comment by skippy** [comment]
and values are stored in `config.json`.  See https://github.com/sjifire/website/blob/main/admin/config.yml#L161 for possible burn status and ban status options
