### ISSUE TITLE
add facebook metatags

### ISSUE THREAD

**Issue by skippy** [sjifire/website#71]
as discussed, the flow is to post on the website then post a summary on facebook with a link back to the site. 

you mentioned some ways to make that 'better', such as a default img, or other meta data.  Let's do that!

**Comment by skippy** [comment]
added some basic openGraph tags via #66

**Comment by icegulch** [comment]
Yeah, I've done this a few times now, so hopefully I can recycle some code and be pretty quick. In your case, you probably just want to make sure you have something nice, then in cases where we know there are good imagery (posts), use those instead of the default?

**Comment by skippy** [comment]
I think we can grab the featured image, and if there isn't one, have a fallback like the one here: https://www.sjifire.org/news/2021-12-21-why-do-we-respond-to-medical-calls/

**Comment by icegulch** [comment]
just added some simple logic for this in `iss71` branch. on 'news-article' pages, use the featured image; else, use a default that's set in `site.json`. so, it's editable within the admin UI (if you want)

**Comment by icegulch** [comment]
oh, if you deploy, let's test with: https://developers.facebook.com/tools/debug/
