### ISSUE TITLE
admin subdomain vs sub-site

### ISSUE THREAD

**Issue by skippy** [sjifire/website#72]
right now the admin is a sub-domain.  This works, however it has run into issues with codifying the `netlify.toml` document.  If we are to use `netlify.toml` then we probably either need to:
* have admin move to `/admin`, or
* reorganize the file structure of the repo to something like `main_site/` and `admin/`

and of course, this assumes that having the build parameters within`netlify.toml` is worth it!  It may not be.  Lets discuss and then fix and close out

**Comment by icegulch** [comment]
We certainly can do this. Having the admin on a separate, generic Netlify domain was just to avoid having to move up to a paid plan (especially while we were feeling things out). For other sites, I often have a /public or /_site folder and the /admin inside of that.

**Comment by skippy** [comment]
how does that force us to a paid plan?  Lets discuss in chat later?

**Comment by skippy** [comment]
moved to /admin awhile back...closing
