### ISSUE TITLE
review document storage

### ISSUE THREAD

**Issue by skippy** [sjifire/website#75]
is there a reason to put it up on the website vs having it link to a public read-only OneDrive folder? 

Honestly, I'm wondering if we made the wrong choice here and should quickly pivot?  Thoughts?  see https://www.orcasfire.org/

**Comment by icegulch** [comment]
I'll defer to you here, since you know what might be easiest for admin users. If there's something like OneDrive that the team is familiar with, I'm all for it. It'd just mean changing the "file" field to a string field, I think.

**Comment by skippy** [comment]
Let's discuss this a bit offline?.  There is a tradeoff between just dumping it all onto OneDrive and having a large link to a folder structure vs being able to better organize it here with a web page in front of it.  

I'm going back and forth.  BECAUSE we already started down this route, I'm inclined to continue, esp. as it allows us to put a nice focused webpage on top of the repository.... and IF the repo gets too large and slow, we can then revisit git lfs or just linking to OneDrive files directly....

but lets chat

**Comment by skippy** [comment]
I'm going to close this.  I like how the setup on the site is evolving... lets see how it flows when we open up admin access, and if it is clunky or slow, we can readdress then.
