### ISSUE TITLE
beef up contact us page

### ISSUE THREAD

**Issue by skippy** [sjifire/website#79]
like https://www.orcasfire.org/contact/

* more contact info
* office hrs
* better copy
* put map to the left?  or just drop it all together?
* formal complaint process document

**Comment by skippy** [comment]
also add media section with info if it is a media request

**Comment by icegulch** [comment]
Yeah, theirs looks nice. It's a WP theme ("Astra").

Regardless, V2 will be the time to explore multi-column layouts for highly modeled pages, I think.

**Comment by skippy** [comment]
#Contact

##We would love to hear from you

Thank you for contacting us. We will review and respond to online correspondence during our administrative office hours, 8 a.m. to 4 p.m., Monday through Friday.

Please do not submit medical inquiries online. Submit all emergency medical inquiries through the Emergency Dispatch Center by calling 911 or the Non-Emergency Line at 360-378-4151.

Your Name: 
Your Email:
Your Message: 


(SIDEBAR)
Emergency CALL 911

San Juan Fire District #3
1011 Mullis St, 
Friday Harbor, WA 98250

Telephone: (360) 378-5334
Fax: 360-378-2591
Dispatch:
  Emergency: 911
  Non Emergency: (360) 378-4151 

Office Hours
*Not Open to the Public* during Covid Pandemic
Monday-Friday 8am-4pm Except Holidays

Links:
* Public Information Request Form PDF
* Citizen Complaint Process & Form PDF

Optional: google map of office location

**Comment by skippy** [comment]
this will address #80
