### ISSUE TITLE
add public info request form

### ISSUE THREAD

**Issue by skippy** [sjifire/website#80]
to governance page

**Comment by icegulch** [comment]
Netlify allows you to have > 1 form, so if we know what fields we'd like and to whom the message should be sent, we're off to the races.

**Comment by skippy** [comment]
I think they want to keep this as a PDF form for now... so I need to get it first off and then post it.  I think they want it as a doc so they can easily save rather than have it go to someones email

**Comment by skippy** [comment]
added to ticket #79. CLOSED! :)
