### ISSUE TITLE
add external resources / useful links section

### ISSUE THREAD

**Issue by skippy** [sjifire/website#81]
can be in the footer, or contact page?  

do we want to do something similar to the orcasfire footer?  We have 3-5 links we'll want to make available

**Comment by icegulch** [comment]
Sure! Yeah, V1 was ultra-simple, huh? ;)

The footer is usually the perfect place for links that don't seem to fit in the main menu.

**Comment by skippy** [comment]
* [San Juan County Department of Emergency Management](https://www.islandsready.org/)
* [SJC Covid Info](https://www.sanjuanco.com/1668/2019-Novel-Coronavirus)
* [SJC Fire Marshal](https://www.sanjuanco.com/1088/Fire-Marshal)

but lets plan for up-to 5

**Comment by icegulch** [comment]
See branch `iss81`. I didn't model it yet. Sometimes it can be worth waiting until the "dust" settles before providing admin access, especially as the site is getting re-organized regularly, but totally your call (obviously!). :)
