### ISSUE TITLE
add facebook widget

### ISSUE THREAD

**Issue by skippy** [sjifire/website#82]
lets see if we want to do this in v2, but easy to punt to v3 if needed

**Comment by icegulch** [comment]
they usually just have some embed code you can grab. do you know where it might go? home?

**Comment by skippy** [comment]
the old site had one, though honestly for now it is going to mirror the website to a huge degree.... so lets keep this on the back burner for a bit and see how the website and FB group settle out

**Comment by skippy** [comment]
the new site layout makes this perfect!  We can compute the right iframe needed here: https://developers.facebook.com/docs/plugins/page-plugin/

and then place it in.  However, we'll probably need to wrap it in a div with appropriate styles

**Comment by skippy** [comment]
this is in, though it needs a little styling cleanup; right now it is using the widget class, which may not be right...

BUT, I think this is good enough to go live with as-is and we fix it up later.
