### ISSUE TITLE
callout/highlight for important documents

### ISSUE THREAD

**Issue by skippy** [sjifire/website#85]
does it make sense to highlight common documents in the design?  Things like planning documents, budget, etc?

I can see us having 3-8 documents listed at any given point.  

this is a little time sensitive as important votes are coming up that we'll need to point people to docs that don't fit in the board meetings section.  lets aim for v1+ or the first sprint of v2.

**Comment by icegulch** [comment]
by "highlight common documents", do you mean literally highlight them (background color or icon) or draw them onto another page?

would it be too "lazy" to have an "Other Documents" section of the Governance page? or maybe we need a "Documents" page?

**Comment by skippy** [comment]
AH!  I meant more as a little widget/area on the documents section (where all the white space is on the right side from upcoming meetings/above past meetings?) where we can link to 4-6 important documents?  I don't think we need a separate page for just documents, though we could see about a sub-page for board meetings... I'm just not sure we're there yet I would say lets not and just keep focused on where to put links to these common documents.

**Comment by skippy** [comment]
I'm moving this down as the highlighted docs aren't ready yet :/.
