### ISSUE TITLE
add press releases

### ISSUE THREAD

**Issue by skippy** [sjifire/website#99]
and then expose under 92

**Comment by skippy** [comment]
all the press releases are uploaded... now we just need a landing page.  Punting this to you @icegulch  :)

**Comment by icegulch** [comment]
Just pushed up a concept that leverages the "governance" design. Let me know what you think.

**Comment by icegulch** [comment]
oh, branch is `iss99`

**Comment by skippy** [comment]
per discussion, and PR #130 looking to add a separate PR page with cards showing a lede or img of the pdf, with accordion for the rest.

**Comment by skippy** [comment]
@icegulch the rewrite of the history for cleaning it up for LFS caused this issue to be scrambled and the PR closed.  I moved over the `src/_data/media_releases.js` over to master, but since we discussed having a separate page, I didn't create a new branch and migrate the `news.njk` file over... the pertinent portion is here:
```njk
    <aside class="l-grid__sidebar">
      {% for year, set in media_releases | groupby('year') | dictsort | reverse %}
        <details class="block-content" {{ 'open' if loop.first }}>
          <summary class="sidebar__heading">Media Releases: {{ year }}</summary>
          <dl class="sidebar__desc-list">
            {% for media_release in set | reverse %}
              <dt>
                {{ media_release.date | postDateTerseNoYearISO }}
              </dt>
              <dd>
                <a href="{{ media_release.document }}">
                  {{ media_release.title }}
                </a>
              </dd>
            {% endfor %}
          </ul>
        </details>
      {% endfor %}
    </aside>
```

**Comment by icegulch** [comment]
Hi, @kvenegassjifire & @skippy! It should be fairly straightforward to bring these back. I can re-integrate them on "News" (see attached) and create a new page (concept attached). What do you think?

![media-releases-news-landing-v1](https://user-images.githubusercontent.com/794708/211213450-6eb4b18c-ee37-4fcd-991e-aa391bcd53d5.png)
![SJIFR-Media-Releases-V1](https://user-images.githubusercontent.com/794708/211213455-c16d5443-eba8-4365-bfb5-cc4aade5ae2e.png)

**Comment by skippy** [comment]
@kvenegassjifire this is really up your alley; thoughts?  

@icegulch the challenge will be is there may be a lot of them over a number of yrs... so we may want to collapse them by year, like the governance page.

**Comment by icegulch** [comment]
Ah, good point. Would something like this with collapsing / expanding sections work? The current year would be open by default in this concept.

![SJIFR-Media-Releases-V2](https://user-images.githubusercontent.com/794708/211704677-566943b5-ddf6-4a10-acdc-991a158a8d50.png)

**Comment by skippy** [comment]
Yep!!  That works!

**Comment by skippy** [comment]
want to open a PR so I can take a look at the code?  It has been awhile but I'm also trying to remember why we wanted to show an img, vs just a text title hyperlinked to the document?  Would that be easier in this case?

anyway, throw the code up and I'll take a peek!

**Comment by icegulch** [comment]
hey, @skippy! indeed, not including an image preview would be easier / faster. i was just going off a comment you made above ("add a separate PR page with cards showing a lede or img of the pdf"), but i'm more than happy to switch.

either way, might be nice to restrict the image helper to markdown blobs somehow? that way, cloudinary url strings included at the template level wouldn't get overridden by `eleventy.js`... just thinking extemporaneously, of course.

**Comment by skippy** [comment]
@icegulch yeah, sorry...I'm scratching my head as to why I asked for an img a year ago rather than just a title... ugh.

as for the image helper, are you talking about this bit of code? https://github.com/sjifire/website/blob/main/src/admin/editor-component-image.js

**Comment by icegulch** [comment]
Hey, @skippy! To be honest, I kinda like the PDF thumbnail, and Cloudinary makes it easy to generate! But, like I said: 100% up to y'all. Happy to KISS!

Meantime, the bit of code that I think affects images _globally_ is this: https://github.com/sjifire/website/blob/main/.eleventy.js#L164

Maybe I was in a older branch, tho? Or maybe it has something to do with Git LFS?

**Comment by skippy** [comment]
I'm fine either way!  Just throwing it out there as an option if that is
easier to you.

As for that JS code; lets chat on the phone when you have a chance?

**Comment by icegulch** [comment]
Prolly can chat today between 10:30a-12p PT, if that'd work for you. Otherwise, I'm around all weekend.

**Comment by icegulch** [comment]
Just pushed up a quick redux, @skippy. Here's what it should give us (much "shorter" page, ultimately!):

![Screenshot 2023-02-06 at 14-41-42 Media Releases San Juan Island Fire and Rescue](https://user-images.githubusercontent.com/794708/217094465-270ca771-d8db-44da-bd19-528923fe6eb9.png)

**Comment by skippy** [comment]
@icegulch looks good! where do you think it should live?  I wonder if it should be under news, but on the home page, mixed in with news?  too complicated or what do you think?  Just thinking outload

**Comment by icegulch** [comment]
hey, @skippy! yeah, I was thinking under News, with an appearance in the sidebar of the news page. if you wanted to add it to the homepage, i could see a couple of spots: 1) right below the 4 or so news cards or right under the burn status widget but above the stats widget (maybe limited to the 3 most recent). i don't know...just spitballing there... thoughts?

**Comment by skippy** [comment]
Hey,
Let’s go ahead and put it under news, and we’re you thinking as a sidebar
as well as it’s own page?  Or just one page.

Let’s get it up and I can fiddle with the home page separately, if that
sounds good to you?

**Comment by icegulch** [comment]
@skippy,

Oh, let's see if we're on the same page:

1. Media Releases as standalone page under "News" main nav
2. Latest "N" releases on News page as sidebar (I think this is mocked up in the `iss99` branch...
3. On homepage under News stories (this is really your call...maybe you don't need them on the homepage?)

Happy to make a `PR` if we're good to go.

**Comment by icegulch** [comment]
Can do. FWIW, there's still _Lorem ipsum_ under the Media Release page heading, so I won't do a `PR` if that's okay. Attaching screenshots of what it should look like in `iss99` branch:

![news-home](https://user-images.githubusercontent.com/794708/217945127-8e420ccf-90ae-476d-852a-f3be52ad1abf.png)
![media-releases-page](https://user-images.githubusercontent.com/794708/217945139-8729f0e5-f3c9-4386-9621-f748cd0274c9.png)
![menu](https://user-images.githubusercontent.com/794708/217945142-f003f223-648f-4fed-95d1-ca007a50a0d7.png)

**Comment by skippy** [comment]
Go ahead and do a pr; we can make that an editable field in the admin and
clear it if we can’t come up with copy.

Thanks!

**Comment by icegulch** [comment]
Hmmm...it says there's "nothing to compare"...what have I done wrong? It is an old branch...

https://github.com/sjifire/website/compare/iss99?expand=1

**Comment by skippy** [comment]
Huh. I wasn't expecting that. That means either branch was completely modified. We did that when the LFS changes went in but I thought we branched after that. Perhaps not. 


I can fix this but iss99 branch is borked. I'll create a new one with your changes cherry-picked on over. Give me a few days.

**Comment by icegulch** [comment]
Sorry about that. Indeed, we had stubbed out the design a ways back, so it's probably got some legacy issues. Anyhow, let me know if you need any help migrating. Shouldn't be a ton of affected files.

**Comment by skippy** [comment]
fixed!  I re-enabled imgs as I think it looks better, but easy to turn on/off based upon feedback.  thanks!
